export const mockEmbeddings = [
  {
    name: 'ImageNet-ResNet50',
    model: 'ResNet50',
    dimensions: 2048,
    vocabularySize: null,
    preprocessing: 'Image resizing, normalization',
    trainingData: 'ImageNet dataset',
    language: null,
    license: 'MIT',
    dateCreated: '2021-05-15',
    downloadSize: '100MB'
  },
  {
    name: 'Google AudioSet-Ensemble',
    model: 'Ensemble',
    dimensions: 527,
    vocabularySize: null,
    preprocessing: 'Audio normalization, spectral features',
    trainingData: 'AudioSet dataset',
    language: 'Multilingual',
    license: 'CC BY',
    dateCreated: '2021-07-01',
    downloadSize: '1GB'
  },
  {
    name: 'YouTube FaceNet',
    model: 'FaceNet',
    dimensions: 128,
    vocabularySize: null,
    preprocessing: 'Face alignment, normalization',
    trainingData: 'YouTube Faces dataset',
    language: null,
    license: 'MIT',
    dateCreated: '2021-08-10',
    downloadSize: '200MB'
  },
  {
    name: 'ResNeXt101-C3D',
    model: 'ResNeXt101',
    dimensions: 2048,
    vocabularySize: null,
    preprocessing: 'Video normalization, spatial and temporal features',
    trainingData: 'Kinetics dataset',
    language: null,
    license: 'MIT',
    dateCreated: '2021-09-15',
    downloadSize: '2GB'
  },
  {
    name: 'Google Inception-v4',
    model: 'Inception-v4',
    dimensions: 1536,
    vocabularySize: null,
    preprocessing: 'Image resizing, normalization',
    trainingData: 'ImageNet dataset',
    language: null,
    license: 'MIT',
    dateCreated: '2021-11-01',
    downloadSize: '150MB'
  },
  {
    name: 'Google SoundNet',
    model: 'SoundNet',
    dimensions: 527,
    vocabularySize: null,
    preprocessing: 'Audio normalization, spectral features',
    trainingData: 'YouTube videos',
    language: 'Multilingual',
    license: 'MIT',
    dateCreated: '2022-01-01',
    downloadSize: '500MB'
  },
  {
    name: 'Flickr8k-CNN',
    model: 'CNN',
    dimensions: 4096,
    vocabularySize: null,
    preprocessing: 'Image resizing, normalization',
    trainingData: 'Flickr8k dataset',
    language: null,
    license: 'CC BY',
    dateCreated: '2022-03-01',
    downloadSize: '100MB'
  },
  {
    name: 'OpenPose',
    model: 'OpenPose',
    dimensions: 57,
    vocabularySize: null,
    preprocessing: 'Pose estimation, normalization',
    trainingData: 'COCO dataset',
    language: null,
    license: 'MIT',
    dateCreated: '2022-05-01',
    downloadSize: '1GB'
  },
  {
    name: 'ResNet-18-UCF101',
    model: 'ResNet-18',
    dimensions: 512,
    vocabularySize: null,
    preprocessing: 'Video normalization, spatial features',
    trainingData: 'UCF101 dataset',
    language: null,

license: 'CC BY',
dateCreated: '2022-07-01',
downloadSize: '800MB'
},
{
name: 'Google Magenta PianoGenie',
model: 'PianoGenie',
dimensions: 512,
vocabularySize: null,
preprocessing: 'MIDI data processing, musical features',
trainingData: 'Lakh MIDI dataset',
language: null,
license: 'Apache 2.0',
dateCreated: '2022-09-01',
downloadSize: '200MB'
},
  {
    name: 'GloVe-100D',
    model: 'GloVe',
    dimensions: 100,
    vocabularySize: 400000,
    preprocessing: 'Lowercasing, Stopword Removal',
    trainingData: 'Wikipedia 2014, Gigaword 5',
    language: 'English',
    license: 'CC BY',
    dateCreated: '2021-02-20',
    downloadSize: '350MB'
  },
  {
    name: 'FastText-300D',
    model: 'FastText',
    dimensions: 300,
    vocabularySize: 2000000,
    preprocessing: 'Lowercasing, Stemming',
    trainingData: 'Common Crawl',
    language: 'English',
    license: 'CC BY',
    dateCreated: '2021-04-10',
    downloadSize: '2GB'
  },
  {
    name: 'Word2Vec-300D',
    model: 'Word2Vec',
    dimensions: 300,
    vocabularySize: 3000000,
    preprocessing: 'Lowercasing, Stopword Removal',
    trainingData: 'Google News',
    language: 'English',
    license: 'MIT',
    dateCreated: '2021-08-15',
    downloadSize: '1.5GB'
  },
  {
    name: 'BERT-Base',
    model: 'BERT',
    dimensions: 768,
    vocabularySize: 30522,
    preprocessing: 'Lowercasing, Tokenization',
    trainingData: 'BooksCorpus, English Wikipedia',
    language: 'English',
    license: 'Apache 2.0',
    dateCreated: '2021-10-25',
    downloadSize: '420MB'
  },
  {
    name: 'GloVe-Spanish-100D',
    model: 'GloVe',
    dimensions: 100,
    vocabularySize: 100000,
    preprocessing: 'Lowercasing, Stopword Removal',
    trainingData: 'Spanish Billion Words Corpus',
    language: 'Spanish',
    license: 'CC BY',
    dateCreated: '2021-12-10',
    downloadSize: '200MB'
  },
  {
    name: 'FastText-Multilingual-300D',
    model: 'FastText',
    dimensions: 300,
    vocabularySize: 1000000,
    preprocessing: 'Lowercasing, Stemming',
    trainingData: 'Common Crawl, Wikipedia',
    language: 'Multilingual',
    license: 'CC BY',
    dateCreated: '2022-01-15',
    downloadSize: '4GB'
  },
  {
    name: 'Word2Vec-German-100D',
    model: 'Word2Vec',
    dimensions: 100,
    vocabularySize: 200000,
    preprocessing: 'Lowercasing, Stopword Removal',
    trainingData: 'German Wikipedia, News Articles',
    language: 'German',
    license: 'MIT',
    dateCreated: '2022-03-30',
    downloadSize: '300MB'
  },
  {
    name: 'GloVe-French-200D',
    model: 'GloVe',
    dimensions: 200,
    vocabularySize: 150000,
    preprocessing: 'Lowercasing, Stopword Removal',
    trainingData: 'French Wikipedia, News Articles',
    language: 'French',
    license: 'CC BY',
      dateCreated: '2022-07-10',
      downloadSize: '500MB'
},
{
name: 'BERT-Multilingual-Base',
model: 'BERT',
dimensions: 768,
vocabularySize: 110000,
preprocessing: 'Lowercasing, Tokenization',
trainingData: 'Multilingual Wikipedia, Web Crawl',
language: 'Multilingual',
license: 'Apache 2.0',
dateCreated: '2022-09-01',
downloadSize: '650MB'
},
{
name: 'FastText-Chinese-300D',
model: 'FastText',
dimensions: 300,
vocabularySize: 500000,
preprocessing: 'Lowercasing, Tokenization',
trainingData: 'Chinese Wikipedia, News Articles',
language: 'Chinese',
license: 'CC BY',
dateCreated: '2022-11-30',
downloadSize: '1GB'
}
];
